### ISSUE TITLE
Cannot find module 'undici'

### ISSUE THREAD

**Issue by EliahKagan** [Vampire/setup-wsl#58]
Starting in version 3.1.0, attempting to set up `Debian` on `windows-latest` fails with a `Cannot find module 'undici'` error. This happens with a step written like:

```yaml
    - name: Set up WSL (Windows)
      uses: Vampire/setup-wsl@v3.1.0
      with:
        distribution: Debian
```

The error message is:

```text
Error: Cannot find module 'undici'
Require stack:
- D:\a\_actions\Vampire\setup-wsl\v3.1.0\build\distributions\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:104[8](https://github.com/EliahKagan/setup-wsl-test/actions/runs/9256515712/job/25462635012#step:3:9):15)
    at Function.Module._load (node:internal/modules/cjs/loader:[9](https://github.com/EliahKagan/setup-wsl-test/actions/runs/9256515712/job/25462635012#step:3:10)01:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.2009 (D:\a\_actions\Vampire\setup-wsl\v3.1.0\build\node_modules\@vercel\ncc\dist\ncc\@@notfound.js:1:1)
    at __nccwpck_require__ (D:\a\_actions\Vampire\setup-wsl\v3.1.0\build\webpack:\setup-wsl-ncc-packer\webpack\bootstrap:21:1)
    at Object.8[11](https://github.com/EliahKagan/setup-wsl-test/actions/runs/9256515712/job/25462635012#step:3:12)9 (D:\a\_actions\Vampire\setup-wsl\v3.1.0\build\node_modules\@actions\cache\node_modules\@actions\http-client\lib\index.js:41:1)
    at __nccwpck_require__ (D:\a\_actions\Vampire\setup-wsl\v3.1.0\build\webpack:\setup-wsl-ncc-packer\webpack\bootstrap:21:1)
    at Object.4304 (D:\a\_actions\Vampire\setup-wsl\v3.1.0\build\node_modules\@actions\cache\lib\internal\cacheHttpClient.js:37:1)
    at __nccwpck_require__ (D:\a\_actions\Vampire\setup-wsl\v3.1.0\build\webpack:\setup-wsl-ncc-packer\webpack\bootstrap:21:1)
```

I have verified that this does not occur in 3.0.0, and does occur in 3.1.0. I first saw it in https://github.com/gitpython-developers/GitPython/pull/1917, where it caused all Windows test jobs to fail. I made the simpler repository https://github.com/EliahKagan/setup-wsl-test to test it, which produced [the same failure](https://github.com/EliahKagan/setup-wsl-test/actions/runs/9256515712/job/25462635012) from [this simplified workflow](https://github.com/EliahKagan/setup-wsl-test/commit/d3cf666afb4141aaa0d18f125a069dd8b10d245e). That the problem is new as of 3.1.0 can be verified by checking [these commits](https://github.com/EliahKagan/setup-wsl-test/commits/main/).

**Comment by Vampire** [comment]
I'm sorry, this seems to be a packaging / release bug.
I'll release 3.1.1 in some minutes that should fix it.
