### ISSUE TITLE
v3.1.2: Always fails with "Cannot find module 'undici'"

### ISSUE THREAD

**Issue by kirb** [Vampire/setup-wsl#61]
Seems v3.1.2 is consistently failing with the following:

```
2024-10-18T06:02:27.2912014Z ##[group]Run Vampire/setup-wsl@v3.1.2
2024-10-18T06:02:27.2912543Z with:
2024-10-18T06:02:27.2912789Z   distribution: Ubuntu-22.04
2024-10-18T06:02:27.2913140Z   use-cache: true | false
2024-10-18T06:02:27.2913475Z   set-as-default: true | false
2024-10-18T06:02:27.2913816Z   update: false
2024-10-18T06:02:27.2914067Z env:
2024-10-18T06:02:27.2914322Z   WSLENV: GITHUB_OUTPUT
2024-10-18T06:02:27.2914616Z ##[endgroup]
2024-10-18T06:02:28.4509808Z Error: Cannot find module 'undici'
2024-10-18T06:02:28.4510224Z Require stack:
2024-10-18T06:02:28.4510718Z - D:\a\_actions\Vampire\setup-wsl\v3.1.2\build\distributions\index.js
2024-10-18T06:02:28.4511383Z     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
2024-10-18T06:02:28.4512016Z     at Function.Module._load (node:internal/modules/cjs/loader:986:27)
2024-10-18T06:02:28.4512550Z     at Module.require (node:internal/modules/cjs/loader:1233:19)
2024-10-18T06:02:28.4513077Z     at require (node:internal/modules/helpers:179:18)
2024-10-18T06:02:28.4513887Z     at Object.2009 (D:\a\_actions\Vampire\setup-wsl\v3.1.2\build\node_modules\@vercel\ncc\dist\ncc\@@notfound.js:1:1)
2024-10-18T06:02:28.4515028Z     at __nccwpck_require__ (D:\a\_actions\Vampire\setup-wsl\v3.1.2\build\webpack:\setup-wsl-ncc-packer\webpack\bootstrap:21:1)
2024-10-18T06:02:28.4516267Z     at Object.8119 (D:\a\_actions\Vampire\setup-wsl\v3.1.2\build\node_modules\@actions\cache\node_modules\@actions\http-client\lib\index.js:41:1)
2024-10-18T06:02:28.4517486Z     at __nccwpck_require__ (D:\a\_actions\Vampire\setup-wsl\v3.1.2\build\webpack:\setup-wsl-ncc-packer\webpack\bootstrap:21:1)
2024-10-18T06:02:28.4518637Z     at Object.4304 (D:\a\_actions\Vampire\setup-wsl\v3.1.2\build\node_modules\@actions\cache\lib\internal\cacheHttpClient.js:37:1)
2024-10-18T06:02:28.4519790Z     at __nccwpck_require__ (D:\a\_actions\Vampire\setup-wsl\v3.1.2\build\webpack:\setup-wsl-ncc-packer\webpack\bootstrap:21:1)
2024-10-18T06:02:28.4849357Z Cleaning up orphan processes
```

I changed to `uses: Vampire/setup-wsl@v3.1.1` and it started working again. Related to #58?

Test runs with a minimal test case:

* v3.1.1: https://github.com/kirb/test-repo-please-ignore/actions/runs/11398272887/job/31715030432
* v3.1.2: https://github.com/kirb/test-repo-please-ignore/actions/runs/11398335034/job/31715196594

**Comment by Vampire** [comment]
Argh, yes, same problem most probably sorry.
Give me a minute and 3.1.3 will fix it.

**Comment by kirb** [comment]
Yep it's fixed now. Thanks!
